### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by 30Wedge** [tyagi-iiitv/MIPSIT#1]
Hi,

Are you able to post the source code for Mipsit? Windows binaries were not what I was looking for :)

-Andy

**Comment by tyagi-iiitv** [comment]
Hey Andy, 

I had a hard time finding the source code for MIPSIT, and that's why I put it on github so that other's can get it easily. However, MIPSIT is only available for Windows OS !! Sorry !

**Comment by 30Wedge** [comment]
Thank you for the prompt response!!!
